# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tftp.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(805, 680)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        Dialog.setFont(font)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(10, 20, 781, 641))
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_Fetch = QtWidgets.QWidget()
        self.tab_Fetch.setObjectName("tab_Fetch")
        self.groupBox_EIOCOM2 = QtWidgets.QGroupBox(self.tab_Fetch)
        self.groupBox_EIOCOM2.setGeometry(QtCore.QRect(20, 20, 746, 61))
        self.groupBox_EIOCOM2.setObjectName("groupBox_EIOCOM2")
        self.label = QtWidgets.QLabel(self.groupBox_EIOCOM2)
        self.label.setGeometry(QtCore.QRect(30, 20, 21, 16))
        self.label.setObjectName("label")
        self.lineEdit_IP = QtWidgets.QLineEdit(self.groupBox_EIOCOM2)
        self.lineEdit_IP.setGeometry(QtCore.QRect(50, 20, 121, 20))
        self.lineEdit_IP.setObjectName("lineEdit_IP")
        self.pushButton_Ping = QtWidgets.QPushButton(self.groupBox_EIOCOM2)
        self.pushButton_Ping.setGeometry(QtCore.QRect(220, 20, 75, 23))
        self.pushButton_Ping.setObjectName("pushButton_Ping")
        self.groupBox_File = QtWidgets.QGroupBox(self.tab_Fetch)
        self.groupBox_File.setGeometry(QtCore.QRect(20, 181, 746, 81))
        self.groupBox_File.setObjectName("groupBox_File")
        self.pushButton_Fetch = QtWidgets.QPushButton(self.groupBox_File)
        self.pushButton_Fetch.setGeometry(QtCore.QRect(220, 30, 75, 23))
        self.pushButton_Fetch.setObjectName("pushButton_Fetch")
        self.label_8 = QtWidgets.QLabel(self.groupBox_File)
        self.label_8.setGeometry(QtCore.QRect(30, 30, 51, 16))
        self.label_8.setObjectName("label_8")
        self.comboBox_Name = QtWidgets.QComboBox(self.groupBox_File)
        self.comboBox_Name.setGeometry(QtCore.QRect(80, 30, 81, 22))
        self.comboBox_Name.setObjectName("comboBox_Name")
        self.pushButton_FetchShow = QtWidgets.QPushButton(self.groupBox_File)
        self.pushButton_FetchShow.setGeometry(QtCore.QRect(340, 30, 121, 23))
        self.pushButton_FetchShow.setObjectName("pushButton_FetchShow")
        self.pushButton_Show = QtWidgets.QPushButton(self.groupBox_File)
        self.pushButton_Show.setGeometry(QtCore.QRect(510, 30, 75, 23))
        self.pushButton_Show.setAutoRepeatDelay(298)
        self.pushButton_Show.setObjectName("pushButton_Show")
        self.groupBox_Log = QtWidgets.QGroupBox(self.tab_Fetch)
        self.groupBox_Log.setGeometry(QtCore.QRect(21, 281, 741, 321))
        self.groupBox_Log.setObjectName("groupBox_Log")
        self.pushButton_Clear = QtWidgets.QPushButton(self.groupBox_Log)
        self.pushButton_Clear.setGeometry(QtCore.QRect(650, 290, 75, 23))
        self.pushButton_Clear.setObjectName("pushButton_Clear")
        self.textEdit_Log = QtWidgets.QTextEdit(self.groupBox_Log)
        self.textEdit_Log.setGeometry(QtCore.QRect(20, 20, 611, 291))
        self.textEdit_Log.setObjectName("textEdit_Log")
        self.groupBox_Guest = QtWidgets.QGroupBox(self.tab_Fetch)
        self.groupBox_Guest.setGeometry(QtCore.QRect(20, 91, 746, 71))
        self.groupBox_Guest.setObjectName("groupBox_Guest")
        self.label_2 = QtWidgets.QLabel(self.groupBox_Guest)
        self.label_2.setGeometry(QtCore.QRect(330, 30, 41, 16))
        self.label_2.setObjectName("label_2")
        self.comboBox_Type = QtWidgets.QComboBox(self.groupBox_Guest)
        self.comboBox_Type.setGeometry(QtCore.QRect(380, 30, 81, 22))
        self.comboBox_Type.setObjectName("comboBox_Type")
        self.label_5 = QtWidgets.QLabel(self.groupBox_Guest)
        self.label_5.setGeometry(QtCore.QRect(30, 30, 54, 12))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_Guest)
        self.label_6.setGeometry(QtCore.QRect(180, 30, 54, 12))
        self.label_6.setObjectName("label_6")
        self.comboBox_RackNo = QtWidgets.QComboBox(self.groupBox_Guest)
        self.comboBox_RackNo.setGeometry(QtCore.QRect(90, 30, 51, 22))
        self.comboBox_RackNo.setObjectName("comboBox_RackNo")
        self.comboBox_SlotNo = QtWidgets.QComboBox(self.groupBox_Guest)
        self.comboBox_SlotNo.setGeometry(QtCore.QRect(240, 30, 51, 22))
        self.comboBox_SlotNo.setObjectName("comboBox_SlotNo")
        self.label_7 = QtWidgets.QLabel(self.groupBox_Guest)
        self.label_7.setGeometry(QtCore.QRect(480, 30, 41, 16))
        self.label_7.setObjectName("label_7")
        self.comboBox_CPU = QtWidgets.QComboBox(self.groupBox_Guest)
        self.comboBox_CPU.setGeometry(QtCore.QRect(540, 30, 61, 22))
        self.comboBox_CPU.setObjectName("comboBox_CPU")
        self.tabWidget.addTab(self.tab_Fetch, "")
        self.pushButton_Manual = QtWidgets.QPushButton(Dialog)
        self.pushButton_Manual.setGeometry(QtCore.QRect(710, 10, 75, 23))
        self.pushButton_Manual.setObjectName("pushButton_Manual")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "TFTP Msg"))
        self.groupBox_EIOCOM2.setTitle(_translate("Dialog", "EIOCOM2"))
        self.label.setText(_translate("Dialog", "IP:"))
        self.pushButton_Ping.setText(_translate("Dialog", "Ping"))
        self.groupBox_File.setTitle(_translate("Dialog", "File"))
        self.pushButton_Fetch.setText(_translate("Dialog", "Fetch"))
        self.label_8.setText(_translate("Dialog", "Name:"))
        self.pushButton_FetchShow.setText(_translate("Dialog", "Fetch and Show"))
        self.pushButton_Show.setText(_translate("Dialog", "Show"))
        self.groupBox_Log.setTitle(_translate("Dialog", "Log"))
        self.pushButton_Clear.setText(_translate("Dialog", "Clear"))
        self.groupBox_Guest.setTitle(_translate("Dialog", "Guest"))
        self.label_2.setText(_translate("Dialog", "Type:"))
        self.label_5.setText(_translate("Dialog", "Rack No:"))
        self.label_6.setText(_translate("Dialog", "Slot No:"))
        self.label_7.setText(_translate("Dialog", "CPU:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Fetch), _translate("Dialog", "Fetch"))
        self.pushButton_Manual.setText(_translate("Dialog", "Manual"))

